/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/P_Cell_Attribute_Enhance.lh
 */
export class CellAttributeEnhancePageBase extends Laya.Box {
    public cell_image!: Laya.Image;
    public name_value_label!: Laya.Label;
    public perception_total_value_label!: Laya.Label;
    public agility_total_value_label!: Laya.Label;
    public attack_total_value_label!: Laya.Label;
    public category_value_label!: Laya.Label;
    public cost_cur_value_label!: Laya.Label;
    public exp_cur_value_label!: Laya.Label;
    public perception_cur_value_label!: Laya.Label;
    public agility_cur_value_label!: Laya.Label;
    public attack_cur_value_label!: Laya.Label;
    public attack_bar!: Laya.HScrollBar;
    public agility_bar!: Laya.HScrollBar;
    public perception_bar!: Laya.HScrollBar;
    public confirm_button!: Laya.Button;
}

