/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/P_Info_Page.lh
 */
export class CellInfoPageBase extends Laya.Box {
    public item0Tab!: Laya.Tab;
    public item0Page!: Laya.ViewStack;
}

