/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/info/P_Info_Page_Cell_List_Info.lh
 */
export class CellInfoSubPageBase extends Laya.Box {
    public cell_bg_img!: Laya.Image;
    public state_bg_img!: Laya.Image;
    public state_label!: Laya.Label;
    public name_cur_value_label!: Laya.Label;
    public bread_count_cur_value_label!: Laya.Label;
    public perception_cur_value_label!: Laya.Label;
    public agility_cur_value_label!: Laya.Label;
    public attack_cur_value_label!: Laya.Label;
    public bodysize_cur_value_label!: Laya.Label;
    public category_cur_value_label!: Laya.Label;
    public exp_cur_value_label!: Laya.Label;
    public add_button!: Laya.Button;
    public play_button!: Laya.Button;
    public enhance_button!: Laya.Button;
}

