/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/info/P_Info_Page_Cell_List.lh
 */
export class CellListPageBase extends Laya.Box {
    public cell_list!: Laya.VBox;
    public item0Page!: Laya.ViewStack;
}

