/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/info/P_Info_Page_Cell_List_Body_Enhance.lh
 */
export class CellBodyEnhancePageBase extends Laya.Box {
    public cell_property_point_panel!: Laya.Panel;
    public name_cur_value_label!: Laya.Label;
    public perception_cur_value_label!: Laya.Label;
    public agility_cur_value_label!: Laya.Label;
    public attack_cur_value_label!: Laya.Label;
    public category_cur_value_label!: Laya.Label;
    public cost_cur_value_label!: Laya.Label;
    public desc_label_1!: Laya.Label;
    public exp_cur_value_label!: Laya.Label;
    public confirm_button!: Laya.Button;
    public enhance_button!: Laya.Button;
}

