/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/info/P_Info_Page_Create_Cell.lh
 */
export class CreateCellPageBase extends Laya.Box {
    public cell_image!: Laya.Image;
    public seed_input!: Laya.TextInput;
    public name_input!: Laya.TextInput;
    public cell_color_label!: Laya.Label;
    public attack_bar!: Laya.HScrollBar;
    public perception_bar!: Laya.HScrollBar;
    public agility_bar!: Laya.HScrollBar;
    public agility_cur_value_label!: Laya.Label;
    public attack_cur_value_label!: Laya.Label;
    public perception_cur_value_label!: Laya.Label;
    public confirm_button!: Laya.Button;
}

