/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/info/P_Info_Page_Cell_List_Cell_Info.lh
 */
export class InfoPageCellListCellInfoBase extends Laya.Dialog {
    public sub_title_label!: Laya.Label;
    public confirm_button!: Laya.Button;
    public avatar_image!: Laya.Image;
    public info_label!: Laya.Label;
}

