/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/map/P_Exploration_Setup_Dialog.lh
 */
export class ExplorationSetupDialogBase extends Laya.Dialog {
    public time_cur_label!: Laya.Label;
    public time_bar!: Laya.HSlider;
    public confirm_button!: Laya.Button;
    public cancel_button!: Laya.Button;
}

