/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/map/P_Map_Page.lh
 */
export class MapInfoPageBase extends Laya.Box {
    public name_cur_value_label!: Laya.Label;
    public explore_button!: Laya.Button;
    public count_down_image!: Laya.Image;
    public count_down_value_label!: Laya.Label;
    public cell_avatar!: Laya.Image;
    public gain_button!: Laya.Button;
}

