/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scene/Home.ls
 */
export class HomeBase extends Laya.Scene {
    public info_button!: Laya.Button;
    public map_button!: Laya.Button;
    public reproduce_button!: Laya.Button;
    public leaderborad_button!: Laya.Button;
    public market_button!: Laya.Button;
    public page_stack!: Laya.ViewStack;
    public address_text!: Laya.Label;
}

