/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scene/Login.ls
 */
export class LoginBase extends Laya.Scene {
    public login_button!: Laya.Button;
    public social_button!: Laya.Button;
    public whitepaper_button!: Laya.Button;
    public address_input!: Laya.TextInput;
    public private_input!: Laya.TextInput;
}

