/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scene/Login.ls
 */
export class LoginBase extends Laya.Scene {
    public init_button: Laya.Button;
    public add_button: Laya.Button;
    public get_button: Laya.Button;
}

