/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scene/Login.ls
 */
export class LoginBase extends Laya.Scene {
    public base!: Laya.Box;
    public login_button!: Laya.Button;
    public social_button!: Laya.Button;
    public whitepaper_button!: Laya.Button;
    public input!: Laya.TextInput;
    public story_image!: Laya.Image;
    public message_label!: Laya.Label;
    public skip_button!: Laya.Button;
}

