/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/market/P_Market_Page_Bid_Selected.lh
 */
export class MarketPageBidSelectedBase extends Laya.Box {
    public cell_list!: Laya.Panel;
    public cell_info!: Laya.Box;
    public cell_bg_img!: Laya.Image;
    public category_value_label!: Laya.Label;
    public cost_value_label!: Laya.Label;
    public cancel_button!: Laya.Button;
    public confirm_button!: Laya.Button;
}

