/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/market/P_Market_Page_Ask.lh
 */
export class MarketPageAskBase extends Laya.Box {
    public cell_list!: Laya.VBox;
    public cell_bg_img!: Laya.Image;
    public breed_count_value_label!: Laya.Label;
    public consume_value_llabel!: Laya.Label;
    public cancel_button!: Laya.Button;
    public confirm_button!: Laya.Button;
    public cost_input!: Laya.TextInput;
    public category_group!: Laya.Panel;
}

