/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/market/P_Market_Page.lh
 */
export class MarketPageBase extends Laya.Box {
    public item0Tab!: Laya.Tab;
    public item0Page!: Laya.ViewStack;
}

