/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/market/P_Market_Page_Bid.lh
 */
export class MarketPageBidBase extends Laya.Box {
    public reload_button!: Laya.Button;
    public category_selected_list!: Laya.RadioGroup;
    public market_list!: Laya.VBox;
    public left_button!: Laya.Button;
    public right_button!: Laya.Button;
}

