/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Account: (() => {
      const name = "Account";
      return defineComponent(
        world,
        {
          init:RecsType.Boolean,
          cell_number: RecsType.Number
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    CellProperty: (() => {
      const name = "CellProperty";
      return defineComponent(
        world,
        {
          init:RecsType.Boolean,
          p1: RecsType.Number,
          p2: RecsType.Number,
          p3: RecsType.Number
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Cell: (() => {
      const name = "Cell";
      return defineComponent(
        world,
        {
          init:RecsType.Boolean,
          name:RecsType.BigInt,
          seed: RecsType.BigInt,
          exp:RecsType.Number,
          bread_count:RecsType.Number,
          body_size:RecsType.Number,
          category:RecsType.Number,
          state:RecsType.Number,
          explore_end_time:RecsType.BigInt
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    WorldInfo: (() => {
      const name = "WorldInfo";
      return defineComponent(
        world,
        {
          init:RecsType.Boolean
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
