/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/leaderboard/P_LeaderBoard_Page.lh
 */
export class LeaderBoardPageBase extends Laya.Box {
    public item0Tab!: Laya.Tab;
    public top_list!: Laya.VBox;
    public normal_list!: Laya.VBox;
    public self_info!: Laya.Box;
    public left_button!: Laya.Button;
    public right_button!: Laya.Button;
}

