/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/common/P_Common_Cell_Avatar.lh
 */
export class CellAvatarBase extends Laya.Box {
    public up_part_image!: Laya.Image;
    public down_part_image!: Laya.Image;
    public center_part_image!: Laya.Image;
    public left_part_image!: Laya.Image;
    public right_part_image!: Laya.Image;
    public state_bg_img!: Laya.Image;
    public state_label!: Laya.Label;
}

