/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/common/P_Common_Loading.lh
 */
export class CommonLoadingBase extends Laya.Dialog {
    public loading_image!: Laya.Image;
}

