/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/common/P_Common_Dialog.lh
 */
export class CommonDialogBase extends Laya.Dialog {
    public content_label!: Laya.Label;
    public cancel_button!: Laya.Button;
    public confirm_button!: Laya.Button;
}

