/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/evolution/P_Evolution_Page_Cell_List.lh
 */
export class EvolutionPageCellBase extends Laya.Box {
    public cell_list!: Laya.VBox;
    public cell_bg_img!: Laya.Image;
    public evolution_bg!: Laya.Image;
    public count_down_label!: Laya.Label;
    public count_down_value_label!: Laya.Label;
    public result_button!: Laya.Button;
}

