/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/evolution/P_Evolution_Page.lh
 */
export class EvolutionPageBase extends Laya.Box {
    public item0Tab!: Laya.Tab;
    public item0Page!: Laya.ViewStack;
}

